### ISSUE TITLE
docker安装问题

### ISSUE THREAD

**Issue by ToTIStarTM** [huyikun/BUAADB2022#1]
C盘确实没有容量可以放下docker了。
发的教程Hiper-v win10家庭版不兼容，也搜不到其他教程。

**Comment by huyikun** [comment]
相关教程应该有很多吧 https://blog.csdn.net/w_zhizhu/article/details/120783391
如果实在不好实现 可以先尝试使用mySQL和sql server 先去完成实验内容

**Comment by ToTIStarTM** [comment]
> 

我的c盘容量就无法完成docker的安装 所以只能找预先就改变安装地址的，但是确实没找到，都是装好了之后改
目前打算买个远程服务器部署了，现在正在用mySQL完成实验内容。
