### ISSUE TITLE
RPC服务器不可用

### ISSUE THREAD

**Issue by thewalker88** [huyikun/BUAADB2022#3]
![@QOOE2 PLZJOF~DE_E@$97V](https://user-images.githubusercontent.com/95581666/159690524-b1e762be-52a7-4e38-b041-a3de13dc06c2.png)
一直提示我RPC服务器不可用，试过重启电脑，重装ubuntu，重下docker，都不行

**Comment by huyikun** [comment]
再试试重新安装 wsl， 如果他给的解决方法全部都没有效果 那就先按mySQL SQLServer 实现实验内容吧
