### ISSUE TITLE
连接PostgreSQL时密码无效

### ISSUE THREAD

**Issue by Xcharlie777** [huyikun/BUAADB2022#4]
连接的时候显示FATAL: Invalid username/password,login denied.
试过用root用户的密码也没用

**Comment by dyn1721** [comment]
确定一下不是拿mysql时填的密码去登录 opengauss数据库

**Comment by Xcharlie777** [comment]
那应该用什么密码登录

**Comment by ljx774** [comment]
同问，懵了，opengauss也没设过密码啊

**Comment by Xcharlie777** [comment]
在运行容器的时候就设置了用户名和密码，可以看下当时运行的命令
