### ISSUE TITLE
重下docker失败了

### ISSUE THREAD

**Issue by XXXXXXXXXXXJ** [huyikun/BUAADB2022#6]
Unpacking failed:文件“C:\Program Files\Docker\Docker\com.docker.service”正由另一进程使用，因此该进程无法访问此文件

**Comment by huyikun** [comment]
可以自行去搜索一下 windows 如何 kill 进程

**Comment by XXXXXXXXXXXJ** [comment]
我该kill哪个进程？

**Comment by XXXXXXXXXXXJ** [comment]
能不下docker吗，感觉重装不了。
