### ISSUE TITLE
task1的第二步运行容器输入命令后显示invalid format

### ISSUE THREAD

**Issue by Megrez104** [huyikun/BUAADB2022#8]

**Comment by Megrez104** [comment]
运行容器，输入
docker run --name opengaussdb -p 5432:5432 -e GS_NODENAME=gaussdb -e GS_USERNAME=gaussdb -e GS_PASSWORD=Enmo@123 --privilege=true --restart=always - d enmotech/opengauss:latest 
命令后显示
docker: invalid reference format.
See 'docker run --help'.

**Comment by huyikun** [comment]
-D 之间不要有空格
